# Port du serveur
server.port=8082

# Désactive la bannière Spring Boot (optionnel)
# spring.main.banner-mode=off

# Logs Spring Security (utile pour déboguer)
logging.level.org.springframework.security=DEBUG
